In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd
import time

from bs4 import BeautifulSoup
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

In [2]:
from selenium import webdriver

driver=webdriver.Chrome()

driver.get("https://catalog.onliner.by/mobile")

In [43]:
# Собираем все ссылки на объявления с выбранной страницы
def get_all_links_on_page():
    elements = driver.find_elements(By.CLASS_NAME, value='catalog-form__link')
    # elements = driver.find_elements(by=By.CSS_SELECTOR, value="#container > div > div > div > div > div.catalog-content > div.catalog-wrapper > div > div > div.catalog-form__tabs > div > div > div > div > div.catalog-form__filter-part.catalog-form__filter-part_2 > div.catalog-form__offers > div > div:nth-child(1) > div > div > div.catalog-form__offers-part.catalog-form__offers-part_data > div.catalog-form__description.catalog-form__description_primary.catalog-form__description_base-additional.catalog-form__description_font-weight_semibold.catalog-form__description_condensed-other > a")
    # <a href="https://catalog.onliner.by/mobile/xiaomi/redmi15c8256ebk" class="catalog-form__link catalog-form__link_primary-additional catalog-form__link_base-additional catalog-form__link_font-weight_semibold catalog-form__link_nodecor"> Телефон Xiaomi Redmi 15C 4G 8GB/256GB международная версия (черный) </a>
    ads_list = []
    for element in elements:
        ads_list.append(element.get_attribute('href'))
        # print(element.get_attribute('href'), '\n')

    return ads_list

In [44]:
links = get_all_links_on_page()

In [45]:
links

['https://tech.onliner.by/2026/02/26/rating-smartphones',
 None,
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bka8/prices',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bka8',
 'https://forum.onliner.by/viewtopic.php?t=26103928',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg/prices',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg',
 'https://forum.onliner.by/viewtopic.php?t=26116412',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh/prices',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh',
 'https://forum.onliner.by/posting.php?mode=newtopic&f=33&device=x8c8128wh',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl/prices',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl',
 'https://forum.onliner.by/viewtopic.php?t=26221387',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl/prices',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl',
 'https://forum.onliner.by/posting.php?mode=newtopic&f=33&device=x5dplus4128sl',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu/prices',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu',
 'https://forum.onliner.by/viewtopic.php?t=26226769',
 'https://catalog.onliner.by/mobile/apple/iphone17256bk/prices',
 'https://catalog.onliner.by/mobile/apple/iphone17256bk',
 'https://forum.onliner.by/viewtopic.php?t=26105506',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bk/prices',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bk',
 'https://forum.onliner.by/viewtopic.php?t=26226769',
 'https://catalog.onliner.by/mobile/apple/ip17pro256sl/prices',
 'https://catalog.onliner.by/mobile/apple/ip17pro256sl',
 'https://forum.onliner.by/viewtopic.php?t=26105646',
 'https://catalog.onliner.by/mobile/apple/iphoneduo256ns/prices',
 'https://catalog.onliner.by/mobile/apple/iphoneduo256ns',
 'https://forum.onliner.by/viewtopic.php?t=26225734',
 'https://catalog.onliner.by/mobile/samsung/sms948b12256bk/prices',
 'https://catalog.onliner.by/mobile/samsung/sms948b12256bk',
 'https://forum.onliner.by/viewtopic.php?t=26164647',
 'https://catalog.onliner.by/mobile/poco/f9ultra16512bk/prices',
 'https://catalog.onliner.by/mobile/poco/f9ultra16512bk',
 'https://forum.onliner.by/viewtopic.php?t=26227292',
 'https://catalog.onliner.by/mobile/apple/ip17pro256db/prices',
 'https://catalog.onliner.by/mobile/apple/ip17pro256db',
 'https://forum.onliner.by/viewtopic.php?t=26105646',
 'https://catalog.onliner.by/mobile/xiaomi/note17prom8256bk/prices',
 'https://catalog.onliner.by/mobile/xiaomi/note17prom8256bk',
 'https://forum.onliner.by/viewtopic.php?t=26222053',
 'https://catalog.onliner.by/mobile/samsung/sms938bzkbcau/prices',
 'https://catalog.onliner.by/mobile/samsung/sms938bzkbcau',
 'https://forum.onliner.by/viewtopic.php?t=26012181',
 'https://catalog.onliner.by/mobile/apple/ip18promax256sl/prices',
 'https://catalog.onliner.by/mobile/apple/ip18promax256sl',
 'https://forum.onliner.by/viewtopic.php?t=26225869',
 'https://catalog.onliner.by/mobile/xiaomi/redmin158256bk/prices',
 'https://catalog.onliner.by/mobile/xiaomi/redmin158256bk',
 'https://forum.onliner.by/viewtopic.php?t=26152114',
 'https://catalog.onliner.by/mobile/apple/ip17promax256db/prices',
 'https://catalog.onliner.by/mobile/apple/ip17promax256db',
 'https://forum.onliner.by/viewtopic.php?t=26105644',
 'https://catalog.onliner.by/mobile/xiaomi/xi17t12256gbk/prices',
 'https://catalog.onliner.by/mobile/xiaomi/xi17t12256gbk',
 'https://forum.onliner.by/posting.php?mode=newtopic&f=33&device=xi17t12256gbk',
 'https://catalog.onliner.by/mobile/samsung/sms931blbbcau/prices',
 'https://catalog.onliner.by/mobile/samsung/sms931blbbcau',
 'https://forum.onliner.by/viewtopic.php?t=26012124',
 'https://catalog.onliner.by/mobile/samsung/sms942b12128bk/prices',
 'https://catalog.onliner.by/mobile/samsung/sms942b12128bk',
 'https://forum.onliner.by/viewtopic.php?t=26164754',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bk/prices',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bk',
 'https://forum.onliner.by/viewtopic.php?t=26225869',
 'https://catalog.onliner.by/mobile/xiaomi/note17pro8256bk/prices',
 'https://catalog.onliner.by/mobile/xiaomi/note17pro8256bk',
 'https://forum.onliner.by/posting.php?mode=newtopic&f=33&device=note17pro8256bk',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bu/prices',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bu/used',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bu',
 'https://forum.onliner.by/viewtopic.php?t=26225869',
 'https://catalog.onliner.by/mobile/apple/iphone16pro128dt/prices',
 'https://catalog.onliner.by/mobile/apple/iphone16pro128dt',
 'https://forum.onliner.by/viewtopic.php?t=25950483',
 'https://catalog.onliner.by/mobile/oneplus/op1516512glsd/prices',
 'https://catalog.onliner.by/mobile/oneplus/op1516512glsd',
 'https://forum.onliner.by/viewtopic.php?t=26134866',
 'https://catalog.onliner.by/mobile/apple/aip16128blk/prices',
 'https://catalog.onliner.by/mobile/apple/aip16128blk/used',
 'https://catalog.onliner.by/mobile/apple/aip16128blk',
 'https://forum.onliner.by/viewtopic.php?t=25950422',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bk/prices',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bk/used',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bk',
 'https://forum.onliner.by/viewtopic.php?t=26103928',
 'https://catalog.onliner.by/mobile/apple/ip18pro256gl/prices',
 'https://catalog.onliner.by/mobile/apple/ip18pro256gl',
 'https://forum.onliner.by/viewtopic.php?t=26226769',
 'https://catalog.onliner.by/mobile/apple/iphone15/prices',
 'https://catalog.onliner.by/mobile/apple/iphone15',
 'https://forum.onliner.by/viewtopic.php?t=25732484']

In [46]:
# Переход на следующую страницу через нажатие на кнопку
def click_next_page():
    clickable_element = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, '/html/body/div[2]/div/div/div/div/div/div/div/div/div[2]/div[1]/div/div/div[4]/div/div/div/div/div[3]/div[3]/a'))
    )

    clickable_element.click()

In [47]:
click_next_page()

In [48]:
len(links)

95

In [49]:
clear_links = []

for item in links:
    if item == None or 'forum.' in item or 'tech.' in item:
        pass
    else:
        clear_links.append(item)

len(clear_links)

63

In [50]:
very_clear_links = []

for item in clear_links:
    if 'prices' in item or 'reviews' in item or 'used' in item:
        pass
    else:
        very_clear_links.append(item)

len(very_clear_links)

30

In [51]:
def clean_links(links: list):
    print(f'Start size of links list: {len(links)}')
    clear_links = []
    very_clear_links = []

    for item in links:
        if item == None or 'forum.' in item or 'tech.' in item:
            pass
        else:
            clear_links.append(item)
    print(f'Current size of links list: {len(clear_links)}')

    for item in clear_links:
        if 'prices' in item or 'reviews' in item or 'used' in item:
            pass
        else:
            very_clear_links.append(item)
    print(f'Finish size of links list: {len(very_clear_links)}')

    return very_clear_links

In [52]:
very_clear_links

['https://catalog.onliner.by/mobile/samsung/sms731b8256bka8',
 'https://catalog.onliner.by/mobile/honor/x9d12256fg',
 'https://catalog.onliner.by/mobile/honor/x8c8128wh',
 'https://catalog.onliner.by/mobile/honor/hx7e6256gllbl',
 'https://catalog.onliner.by/mobile/honor/x5dplus4128sl',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bu',
 'https://catalog.onliner.by/mobile/apple/iphone17256bk',
 'https://catalog.onliner.by/mobile/apple/ip18pro256bk',
 'https://catalog.onliner.by/mobile/apple/ip17pro256sl',
 'https://catalog.onliner.by/mobile/apple/iphoneduo256ns',
 'https://catalog.onliner.by/mobile/samsung/sms948b12256bk',
 'https://catalog.onliner.by/mobile/poco/f9ultra16512bk',
 'https://catalog.onliner.by/mobile/apple/ip17pro256db',
 'https://catalog.onliner.by/mobile/xiaomi/note17prom8256bk',
 'https://catalog.onliner.by/mobile/samsung/sms938bzkbcau',
 'https://catalog.onliner.by/mobile/apple/ip18promax256sl',
 'https://catalog.onliner.by/mobile/xiaomi/redmin158256bk',
 'https://catalog.onliner.by/mobile/apple/ip17promax256db',
 'https://catalog.onliner.by/mobile/xiaomi/xi17t12256gbk',
 'https://catalog.onliner.by/mobile/samsung/sms931blbbcau',
 'https://catalog.onliner.by/mobile/samsung/sms942b12128bk',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bk',
 'https://catalog.onliner.by/mobile/xiaomi/note17pro8256bk',
 'https://catalog.onliner.by/mobile/apple/ip18promax256bu',
 'https://catalog.onliner.by/mobile/apple/iphone16pro128dt',
 'https://catalog.onliner.by/mobile/oneplus/op1516512glsd',
 'https://catalog.onliner.by/mobile/apple/aip16128blk',
 'https://catalog.onliner.by/mobile/samsung/sms731b8256bk',
 'https://catalog.onliner.by/mobile/apple/ip18pro256gl',
 'https://catalog.onliner.by/mobile/apple/iphone15']

In [53]:
links_list = []
try:
    for iter in range(0, 5, 1):
        links_list += get_all_links_on_page()
        click_next_page()
except:
    print("All done")
    clean_links_list = clean_links(links_list)
finally:
    print("All done")
    clean_links_list = clean_links(links_list)

All done
Start size of links list: 99
Current size of links list: 67
Finish size of links list: 30
All done
Start size of links list: 99
Current size of links list: 67
Finish size of links list: 30

In [54]:
clean_links_list

['https://catalog.onliner.by/mobile/apple/iphone16pm256nt',
 'https://catalog.onliner.by/mobile/xiaomi/xia17pm16512cwh',
 'https://catalog.onliner.by/mobile/google/pixel1112256fr',
 'https://catalog.onliner.by/mobile/poco/x8pro8256glbk',
 'https://catalog.onliner.by/mobile/apple/ip18pro256sl',
 'https://catalog.onliner.by/mobile/samsung/sma576bdbfcau',
 'https://catalog.onliner.by/mobile/apple/ip18pro512bu',
 'https://catalog.onliner.by/mobile/samsung/smf971bzkbskz',
 'https://catalog.onliner.by/mobile/poco/f9ultra12256bk',
 'https://catalog.onliner.by/mobile/samsung/sms931blbccau',
 'https://catalog.onliner.by/mobile/apple/iphoneduo512ns',
 'https://catalog.onliner.by/mobile/samsung/sma075fzkdcau',
 'https://catalog.onliner.by/mobile/apple/ip17pro256co',
 'https://catalog.onliner.by/mobile/apple/iphone17256wh',
 'https://catalog.onliner.by/mobile/apple/ip17promax256sl',
 'https://catalog.onliner.by/mobile/xiaomi/xi17tpro12256gbk',
 'https://catalog.onliner.by/mobile/samsung/sms948bzkccau',
 'https://catalog.onliner.by/mobile/apple/iphoneduo512sw',
 'https://catalog.onliner.by/mobile/honor/600prod12512glbk',
 'https://catalog.onliner.by/mobile/apple/iphoneair256sb',
 'https://catalog.onliner.by/mobile/honor/6008256dsglor',
 'https://catalog.onliner.by/mobile/honor/x9d12256mb',
 'https://catalog.onliner.by/mobile/samsung/galaxys268128bk',
 'https://catalog.onliner.by/mobile/xiaomi/xmixflipg12512b',
 'https://catalog.onliner.by/mobile/xiaomi/note17prom8512bk',
 'https://catalog.onliner.by/mobile/apple/iphone15promaxnt',
 'https://catalog.onliner.by/mobile/poco/x8promax256glbk',
 'https://catalog.onliner.by/mobile/xiaomi/xia17pro12256cwh',
 'https://catalog.onliner.by/mobile/huawei/hedlx912256bk',
 'https://catalog.onliner.by/mobile/samsung/sms938bzkccau']

In [55]:
with open('links.txt', 'a', encoding='utf-8') as file:
    for link in clean_links_list:
        file.write(link + '\n')

In [ ]:
for link in clean_links_list:
    driver.get(link)
    get_characteristics()
    break

NameError: name 'clean_links_list' is not defined

In [ ]:
def get_characteristics():
    character_dict = {}
    elements = driver.find_elements(By.CLASS_NAME, value='product-specs__table')
    for item in elements: 
            tds = item.find_elements(By.TAG_NAME, value='td')
            for i in range(0, len(tds)):
                if tds[i].rect['width'] == 453:
                    character_dict.update({tds[i].text:tds[i+1].text})
    
    print(character_dict)       

get_characteristics()

{'Дата выхода на рынок': '2026 г.', '2026 г.': 'Описание\n⚠️ В зависимости от точной модели устройства, адаптер питания может отсутствовать в комплекте поставки.\n\n✅Redmi Note 17 Pro Max 5G - это мощный современный смартфон с большим AMOLED-дисплеем диагональю 6.83 дюйма и частотой обновления 120 Гц, что обеспечивает плавную работу интерфейса и яркую, насыщенную картинку. Экран защищен стеклом Gorilla Glass Victus 2, а корпус выполнен из сочетания пластика и стекла, что делает устройство одновременно легким и прочным.\n\n✅Смартфон работает на платформе Qualcomm Snapdragon 6 Gen 5, выполненной по 4-нм техпроцессу, обеспечивая высокую производительность и энергоэффективность. Оперативная память LPDDR5X (8 или 12 ГБ) и быстрый накопитель UFS 4.0 объемом до 512 ГБ дают возможность комфортной работы с современными приложениями и играми.\n\n✅Redmi Note 17 Pro Max 5G оснащен продвинутой камерой:основная камера на 50 Мп с оптической стабилизацией и автофокусом, а также широкоугольный модуль на 8 Мп. Для селфи предусмотрена фронтальная камера на 32 Мп. Среди особенностей - поддержка съемки видео в 4K, быстрая зарядка мощностью 100 Вт, встроенный сканер отпечатка пальца в экране и поддержка двойных SIM-карт (nano-SIM + nano-SIM/eSIM).\n\n✅Смартфон выделяется емким аккумулятором на 10000 мА·ч, защитой от воды и пыли по стандарту IP69K, наличием NFC, ИК-порта, Bluetooth 6.0 и Wi-Fi 6. Работает на базе Android 16 с фирменной оболочкой HyperOS 3.1, обеспечивающей удобный пользовательский опыт и широкие возможности кастомизации.\nЧитать дальше', 'Операционная система': 'Android', 'Android': 'Версия ОС на момент выхода', 'Версия ОС на момент выхода': 'Android 16', 'Android 16': 'Оболочка', 'Оболочка': 'Hyper OS', 'Hyper OS': 'Размер экрана', 'Размер экрана': '6.83"', '6.83"': 'Разрешение экрана', 'Разрешение экрана': '1280x2772', '1280x2772': 'Технология экрана', 'Технология экрана': 'AMOLED', 'AMOLED': 'Частота обновления экрана', 'Частота обновления экрана': '120 Гц', '120 Гц': 'Объем оперативной памяти', 'Объем оперативной памяти': '8 ГБ', '8 ГБ': 'Объем встроенной памяти', 'Тип оперативной памяти': 'LPDDR5X', 'LPDDR5X': 'Виртуальное расширение оперативной памяти', 'Виртуальное расширение оперативной памяти': '8 ГБ', 'Объем встроенной памяти': '256 ГБ', '256 ГБ': 'Тип встроенной памяти', 'Тип встроенной памяти': 'UFS 4.1', 'UFS 4.1': 'Количество точек матрицы основной камеры', 'Количество точек матрицы основной камеры': '50 Мп', '50 Мп': 'Характеристики блока камер', 'Характеристики блока камер': '50 Мп, 26 мм, f/1.5, 0.8 мкм, линзы 6P, PDAF, широкоугольный\n8 Мп, 15 мм, f/2.2, 1/4.0", 1.12 мкм, FOV 120˚, сверхширокоугольный', '50 Мп, 26 мм, f/1.5, 0.8 мкм, линзы 6P, PDAF, широкоугольный\n8 Мп, 15 мм, f/2.2, 1/4.0", 1.12 мкм, FOV 120˚, сверхширокоугольный': 'Максимальное разрешение видео', 'Максимальное разрешение видео': '3840x2160 (30 кадров/с)', '3840x2160 (30 кадров/с)': 'Беспроводная зарядка', 'Беспроводная зарядка': '', '': 'Акция', 'Быстрая зарядка': 'USB Power Delivery, Xiaomi HyperCharge', 'USB Power Delivery, Xiaomi HyperCharge': 'Поддержка карт памяти', 'Поддержка карт памяти': '', 'Количество физических SIM-карт': '2', '2': 'Модули камер', 'Формат SIM-карты': 'nano-SIM, eSIM', 'nano-SIM, eSIM': 'Процессор', 'Платформа': 'Qualcomm Snapdragon', 'Qualcomm Snapdragon': 'Процессор', 'Процессор': 'Qualcomm Snapdragon 6 Gen 5', 'Qualcomm Snapdragon 6 Gen 5': 'Тактовая частота процессора', 'Тактовая частота процессора': '2 600 МГц', '2 600 МГц': 'Количество ядер', 'Количество ядер': '8 (4+4)', '8 (4+4)': 'Микроархитектура ЦПУ', 'Микроархитектура ЦПУ': 'ARM Cortex-A78 2600 МГц + ARM Cortex-A55 2000 МГц', 'ARM Cortex-A78 2600 МГц + ARM Cortex-A55 2000 МГц': 'Разрядность процессора', 'Разрядность процессора': '64 бита', '64 бита': 'Техпроцесс', 'Техпроцесс': '4 нм', '4 нм': 'Графический ускоритель', 'Графический ускоритель': 'Qualcomm Adreno 812', 'Qualcomm Adreno 812': 'Конструкция', 'Конструкция корпуса': 'моноблок', 'моноблок': 'Стереодинамики', 'Стереодинамики': '', 'Материал граней': 'пластик', 'пластик': 'Цвет граней', 'Материал задней крышки': 'пластик', 'Цвет граней': 'серебристый', 'серебристый': 'Цвет задней крышки', 'Цвет задней крышки': 'белый', 'белый': 'Цвет фронтальной панели', 'Цвет фронтальной панели': 'черный', 'черный': 'Ударопрочный корпус', 'Ударопрочный корпус': '', 'Пыле- и влагозащита': 'IP66, IP68, IP69, IP69K', 'IP66, IP68, IP69, IP69K': 'Встроенные магниты (для зарядки и аксессуаров)', 'Встроенные магниты (для зарядки и аксессуаров)': '', 'Физическая QWERTY-клавиатура': '', 'Сканер отпечатка пальца': 'оптический', 'оптический': 'Расположение сканера отпечатка пальца', 'Расположение сканера отпечатка пальца': 'встроен в дисплей', 'встроен в дисплей': 'Разблокировка по лицу', 'Разблокировка по лицу': '', 'Функциональные особенности': 'симметричные рамки экрана, работа с мокрым экраном, ИК-передатчик, электронный компас, обратная проводная зарядка', 'симметричные рамки экрана, работа с мокрым экраном, ИК-передатчик, электронный компас, обратная проводная зарядка': 'Размеры и вес', 'Длина': '163.44 мм', '163.44 мм': 'Ширина', 'Ширина': '78.27 мм', '78.27 мм': 'Толщина', 'Толщина': '8.57 мм', '8.57 мм': 'Вес', 'Вес': '229.5 г', '229.5 г': 'Экран', 'Количество цветов экрана': '68 млрд', '68 млрд': 'Разрешающая способность экрана', 'Разрешающая способность экрана': '447 ppi', '447 ppi': 'Соотношение сторон', 'Соотношение сторон': '19.5:9', '19.5:9': 'Яркость экрана (типичная)', 'Яркость экрана (типичная)': '1060 нит', '1060 нит': 'Яркость экрана (пиковая)', 'Яркость экрана (пиковая)': '3500 нит', '3500 нит': 'Защита от царапин', 'Защита от царапин': 'Gorilla Glass Victus 2', 'Gorilla Glass Victus 2': 'Постоянная работа экрана', 'Постоянная работа экрана': '', 'Динамический контроль частоты обновления (LTPO)': '', 'Управление яркостью подсветки экрана': 'PWM Dimming', 'PWM Dimming': 'Частота ШИМ', 'Частота ШИМ': '3 840 Гц', '3 840 Гц': 'Основная камера', 'Основной блок камер': '50 Мп + 8 Мп', '50 Мп + 8 Мп': 'Количество модулей камеры', 'Количество модулей камеры': '2', 'Модули камер': 'широкоугольный, сверхширокоугольный', 'широкоугольный, сверхширокоугольный': 'Встроенная вспышка', 'Встроенная вспышка': '', 'Автоматическая фокусировка': '', 'Тип стабилизации': 'оптическая (OIS), цифровая (EIS)', 'оптическая (OIS), цифровая (EIS)': 'Диафрагма основной камеры', 'Диафрагма основной камеры': 'f/1.5', 'f/1.5': 'Макс. количество кадров в секунду', 'Макс. количество кадров в секунду': '120 кадров/с (Slo-Mo 720P)', '120 кадров/с (Slo-Mo 720P)': 'Фронтальная камера', 'Фронтальная камера': '32 Мп', '32 Мп': 'Характеристики фронтальной камеры', 'Характеристики фронтальной камеры': '32 Мп, f/2.2, 0.61 мкм, линзы 4P, широкоугольный', '32 Мп, f/2.2, 0.61 мкм, линзы 4P, широкоугольный': 'Расположение фронтальной камеры', 'Расположение фронтальной камеры': 'в экране', 'в экране': 'Двойная камера', 'Двойная камера': '', 'Диафрагма фронтальной камеры': 'f/2.2', 'f/2.2': 'Макс. разрешение видео фронтальной камеры', 'Макс. разрешение видео фронтальной камеры': '3840x2160 (4K UHD)', '3840x2160 (4K UHD)': 'Датчики', 'Акселерометр': '', 'Гироскоп': '', 'Датчик освещенности': '', 'Датчик приближения': '', 'Барометр': '', 'Монитор сердечного ритма': '', 'Измерение насыщенности крови кислородом': '', 'GPS': '', 'ГЛОНАСС': '', 'Beidou': '', 'GALILEO': '', 'Поддержка 4G (LTE)': '', 'Поддержка 5G': '', 'Поддерживаемые частоты и полосы': '2G: GSM: B2/B3/B5/B8\n3G: WCDMA: B1/B2/B4/B5/B8\n4G: LTE FDD: B1/B2/B3/B4/B5/B7/B8/B12/B13/B17/B18/B19/B20/ B26/B28/B32/B66\n4G: LTE TDD: B38/B40/B41/B42/B48\n5G: n1/2/3/5/7/8/12/20/26/28/38/40/41/48/66/77/78', '2G: GSM: B2/B3/B5/B8\n3G: WCDMA: B1/B2/B4/B5/B8\n4G: LTE FDD: B1/B2/B3/B4/B5/B7/B8/B12/B13/B17/B18/B19/B20/ B26/B28/B32/B66\n4G: LTE TDD: B38/B40/B41/B42/B48\n5G: n1/2/3/5/7/8/12/20/26/28/38/40/41/48/66/77/78': 'Интерфейсы', 'Bluetooth': '6.0', '6.0': 'Аудиовыход', 'Аудиовыход': 'USB Type-C', 'USB Type-C': 'Wi-Fi', 'Wi-Fi': '802.11ax (Wi-Fi 6)', '802.11ax (Wi-Fi 6)': 'Разъём подключения', 'Разъём подключения': 'USB Type-C 2.0', 'USB Type-C 2.0': 'NFC', 'NFC': '', 'Тип аккумулятора': 'Si-C', 'Si-C': 'Емкость аккумулятора', 'Емкость аккумулятора': '10 000 мА·ч', '10 000 мА·ч': 'Конструкция аккумулятора', 'Конструкция аккумулятора': 'несъемный', 'несъемный': 'Комплектация', 'Комплект поставки': 'кабель USB-A - USB-C, скрепка, документация', 'кабель USB-A - USB-C, скрепка, документация': 'Чехол', 'Чехол': '', 'Перо (стилус)': '', 'Акционное предложение': 'без акции', 'без акции': 'Метки', 'Модель': 'Xiaomi Redmi Note 17 Pro Max', 'Xiaomi Redmi Note 17 Pro Max': 'Метки'}

In [57]:
def get_characteristics():
    character_dict = {}
    character_dict.update({'Название модели': driver.find_element(By.CLASS_NAME, value='catalog-masthead__title').text})
    elements = driver.find_elements(By.CSS_SELECTOR, value='.product-specs__table tr')
    for item in elements: 
        tds = item.find_elements(By.TAG_NAME, value='td')
        if len(tds) == 2:
            if not tds[1].text:
                if tds[1].find_elements(By.CLASS_NAME, value='i-x'):
                    character_dict.update({tds[0].text: 'No'})
                else:
                    character_dict.update({tds[0].text: 'Yes'})
            else:
                character_dict.update({tds[0].text:tds[1].text})
    
    for key,value in character_dict.items():
        print(f'{key}: {value}')  

    return character_dict

In [ ]:

table = pd.DataFrame()
for link in clean_links_list[0:10]:
    driver.get(link)
    
    new_row = pd.DataFrame([get_characteristics()])
    table = pd.concat([table , new_row] , ignore_index=True)
    
    
    



table

Название модели: Телефон Apple iPhone 16 Pro Max 256GB (природный титан)
Дата выхода на рынок: 2024 г.
Отличия от предыдущего поколения: ✅ Дизайн и размер
iPhone 16 Pro Max оснащен увеличенным дисплеем, что полностью соответствует растущим потребностям в использовании смартфонов. При этом не стоит беспокоиться, что физически устройство станет значительно больше. Благодаря уменьшенным рамкам вокруг дисплея, его габариты почти не изменились по сравнению с iPhone 15 Pro Max.

✅ Экран
iPhone 16 Pro Max имеет яркий дисплей с разрешением 2868x1320 пикселей и яркостью до 2000 нит в пике, что обеспечивает четкое изображение даже при ярком солнечном свете.

✅Процессор
Apple решила сделать серьёзный шаг вперёд, перейдя на второе поколение 3-нм технологии с использованием A18 Pro, что позволило значительно улучшить производительность как процессора, так и графики. Чип был специально разработан с учётом интеграции искусственного интеллекта. Это даёт 17%-ное увеличение общей пропускной способности памяти, что также положительно сказывается на работе 6-ядерного графического процессора, который работает до 20% быстрее по сравнению с прошлым поколением.

✅ Камеры
iPhone 16 Pro Max оснащён тремя камерами на задней панели, как и iPhone 15 Pro Max, но эти камеры не идентичны, и есть два значительных улучшения:
- Во-первых, на этот раз у вас есть новая 5-кратная телеобъективная камера, которая заменила 3-кратный зум в 15 Pro Max. Это означает, что вы получите более чёткое изображение при 5X, 10X и большем увеличении, что особенно полезно при съёмке концертов или удалённых объектов.
- Во-вторых, в ультраширокий объектив был установлен новый 48-мегапиксельный сенсор.
- Что касается видеосъёмки, то новинка представляет собой поддержку 4K120. Ранее модели iPhone могли снимать в 120fps только при разрешении 1080p, что не так остро, как 4K.

✅ Беспроводная зарядка
Новые iPhone 16 Pro Max получили улучшенную до 25 Вт мощность беспроводной зарядки через MagSafe и поддержку стандарта Qi2.

✅ Apple Intelligence
Система искуственного интеллекта, которая помогает вам писать, обрабатывать фото и выражать свои мысли добиваясь отличных результатов. Благодаря революционной защите конфиденциальности вы можете быть уверены в том, что никто другой не сможет получить доступ к вашим данным - даже Apple.

✅ Обновленная при помощи ИИ Siri
Теперь голосовой помощник ведет себя более естественно, контекстуально и индивидуально.
*Изменения доступны только на английском языке.
Операционная система: iOS
Версия ОС на момент выхода: iOS 18
Размер экрана: 6.9"
Разрешение экрана: 1320x2868
Технология экрана: OLED (Super Retina XDR)
Частота обновления экрана: 120 Гц
Объем оперативной памяти: 8 ГБ
Виртуальное расширение оперативной памяти: No
Объем встроенной памяти: 256 ГБ
Количество точек матрицы основной камеры: 48 Мп
Характеристики блока камер: 48 Мп, 24 мм, f/1.78, 1/1.28", 1.22 мкм, оптическая стабилизация со сдвигом датчика, широкоугольный

48 Мп, 13 мм, f/2.2, 1/2.55", 0.7 мкм, FOV 120°, сверхширокоугольный

12 Мп, 120 мм, f/2.8, 1/3.06", 1.12 мкм, FOV 20°, оптическая стабилизация, телеобъектив
Максимальное разрешение видео: 3840x2160 (120 кадров/с)
Беспроводная зарядка: 25 Вт
Обратная беспроводная зарядка: No
Быстрая зарядка: Yes
Поддержка карт памяти: No
Количество физических SIM-карт: 1
Формат SIM-карты: nano-SIM, eSIM
Платформа: Apple A
Процессор: Apple A18 Pro
Количество ядер: 6 (2+4)
Разрядность процессора: 64 бита
Техпроцесс: 3 нм
Графический ускоритель: Apple A18 Pro GPU (6 ядер)
Модем: Qualcomm Snapdragon X75
Конструкция корпуса: моноблок
Стереодинамики: Yes
Материал граней: титан
Материал задней крышки: стекло
Цвет граней: титановый
Цвет задней крышки: титановый
Цвет фронтальной панели: черный
Ударопрочный корпус: No
Пыле- и влагозащита: IP68
Встроенные магниты (для зарядки и аксессуаров): Apple MagSafe
Физическая QWERTY-клавиатура: No
Сканер отпечатка пальца: No
Разблокировка по лицу: Yes
Функциональные особенности: симметричные рамки экрана, экран с поддержкой Dolby Vision, кнопка быстрой съемки, интерактивный вырез фронтальной камеры, съемка пространственного фото/видео, электронный компас, настраиваемая кнопка (кнопка действия), обратная проводная зарядка
Длина: 163 мм
Ширина: 77.6 мм
Толщина: 8.25 мм
Вес: 227 г
Количество цветов экрана: 16 млн
Разрешающая способность экрана: 460 ppi
Соотношение сторон: 19.5:9
Яркость экрана (типичная): 1000 нит
Яркость экрана (пиковая): 2000 нит
Защита от царапин: Ceramic Shield
Постоянная работа экрана: Yes
Динамический контроль частоты обновления (LTPO): Yes
Основной блок камер: 48 Мп + 48 Мп + 12 Мп
Количество модулей камеры: 3
Модули камер: телеобъектив, широкоугольный, сверхширокоугольный
Встроенная вспышка: No
Автоматическая фокусировка: Yes
Тип стабилизации: оптическая (OIS), цифровая (EIS)
Оптический зум: 7X (5X на увеличение, 2X на уменьшение)
Цифровой зум: 25X (на увеличение)
Диафрагма основной камеры: f/1.78
Макс. количество кадров в секунду: 240 кадров/с
Фронтальная камера: 12 Мп
Характеристики фронтальной камеры: 12 Мп, 23 мм, f/1.9, 1/3.6", 1 мкм, SL 3D, датчик глубины/биометрический сенсор
Расположение фронтальной камеры: в экране
Двойная камера: No
Диафрагма фронтальной камеры: f/1.9
Макс. разрешение видео фронтальной камеры: 3840x2160 (4K UHD)
Акселерометр: Yes
Гироскоп: Yes
Датчик освещенности: Yes
Датчик приближения: Yes
Барометр: Yes
Монитор сердечного ритма: No
Измерение насыщенности крови кислородом: No
GPS: Yes
ГЛОНАСС: Yes
Beidou: Yes
GALILEO: Yes
Поддержка 4G (LTE): Yes
Поддержка 5G: Yes
Bluetooth: 5.3
Аудиокодеки Bluetooth: SBC, AAC
Аудиовыход: USB Type-C
Wi-Fi: 802.11be (Wi-Fi 7)
Разъём подключения: USB Type-C 3.2 Gen2
NFC: Yes
Тип аккумулятора: Li-ion
Емкость аккумулятора: 4 685 мА·ч
Конструкция аккумулятора: несъемный
Макс. время воспроизведения видео: 33 ч
Макс. время воспроизведения аудио: 105 ч
Комплект поставки: кабель USB-C - USB-C, скрепка, документация
Чехол: No
Перо (стилус): No
Модель: Apple iPhone 16 Pro Max
Метки: Onliner рекомендует, флагман, игровой, 256 ГБ, водонепроницаемый, с ультразумом

,Название модели,Дата выхода на рынок,Отличия от предыдущего поколения,Операционная система,Версия ОС на момент выхода,Размер экрана,Разрешение экрана,Технология экрана,Частота обновления экрана,Объем оперативной памяти,...,Тип аккумулятора,Емкость аккумулятора,Конструкция аккумулятора,Макс. время воспроизведения видео,Макс. время воспроизведения аудио,Комплект поставки,Чехол,Перо (стилус),Модель,Метки
0,Телефон Apple iPhone 16 Pro Max 256GB (природн...,2024 г.,✅ Дизайн и размер\niPhone 16 Pro Max оснащен у...,iOS,iOS 18,"6.9""",1320x2868,OLED (Super Retina XDR),120 Гц,8 ГБ,...,Li-ion,4 685 мА·ч,несъемный,33 ч,105 ч,"кабель USB-C - USB-C, скрепка, документация",No,No,Apple iPhone 16 Pro Max,"Onliner рекомендует, флагман, игровой, 256 ГБ,..."

In [ ]:
model_row.keys()

['Название модели',
 'Дата выхода на рынок',
 'Операционная система',
 'Версия ОС на момент выхода',
 'Оболочка',
 'Размер экрана',
 'Разрешение экрана',
 'Технология экрана',
 'Частота обновления экрана',
 'Объем оперативной памяти',
 'Объем встроенной памяти',
 'Количество точек матрицы основной камеры',
 'Характеристики блока камер',
 'Максимальное разрешение видео',
 'Беспроводная зарядка',
 'Обратная беспроводная зарядка',
 'Быстрая зарядка',
 'Поддержка карт памяти',
 'Количество физических SIM-карт',
 'Формат SIM-карты',
 'Раздельные слоты SIM 2 и карт памяти',
 'Платформа',
 'Процессор',
 'Тактовая частота процессора',
 'Количество ядер',
 'Микроархитектура ЦПУ',
 'Разрядность процессора',
 'Техпроцесс',
 'Графический ускоритель',
 'Конструкция корпуса',
 'Стереодинамики',
 'Материал граней',
 'Материал задней крышки',
 'Цвет граней',
 'Цвет задней крышки',
 'Цвет фронтальной панели',
 'Ударопрочный корпус',
 'Пыле- и влагозащита',
 'Физическая QWERTY-клавиатура',
 'Сканер отпечатка пальца',
 'Расположение сканера отпечатка пальца',
 'Разблокировка по лицу',
 'Функциональные особенности',
 'Длина',
 'Ширина',
 'Толщина',
 'Вес',
 'Количество цветов экрана',
 'Разрешающая способность экрана',
 'Соотношение сторон',
 'Яркость экрана (пиковая)',
 'Защита от царапин',
 'Постоянная работа экрана',
 'Динамический контроль частоты обновления (LTPO)',
 'Основной блок камер',
 'Количество модулей камеры',
 'Модули камер',
 'Встроенная вспышка',
 'Автоматическая фокусировка',
 'Тип стабилизации',
 'Оптический зум',
 'Цифровой зум',
 'Диафрагма основной камеры',
 'Макс. количество кадров в секунду',
 'Фронтальная камера',
 'Характеристики фронтальной камеры',
 'Расположение фронтальной камеры',
 'Двойная камера',
 'Диафрагма фронтальной камеры',
 'Макс. разрешение видео фронтальной камеры',
 'Акселерометр',
 'Гироскоп',
 'Датчик освещенности',
 'Датчик приближения',
 'Барометр',
 'Монитор сердечного ритма',
 'Измерение насыщенности крови кислородом',
 'GPS',
 'ГЛОНАСС',
 'Beidou',
 'GALILEO',
 'Поддержка 4G (LTE)',
 'Поддержка 5G',
 'Поддерживаемые частоты и полосы',
 'Bluetooth',
 'Аудиокодеки Bluetooth',
 'Аудиовыход',
 'Wi-Fi',
 'Разъём подключения',
 'NFC',
 'Тип аккумулятора',
 'Емкость аккумулятора',
 'Конструкция аккумулятора',
 'Макс. время воспроизведения видео',
 'Мощность зарядки',
 'Комплект поставки',
 'Чехол',
 'Перо (стилус)',
 'Акционное предложение',
 'Устройства в комплекте',
 'Модель',
 'Метки']

In [60]:
import csv

table = pd.DataFrame([model_row])
table

,Название модели,Дата выхода на рынок,Отличия от предыдущего поколения,Операционная система,Версия ОС на момент выхода,Размер экрана,Разрешение экрана,Технология экрана,Частота обновления экрана,Объем оперативной памяти,...,Тип аккумулятора,Емкость аккумулятора,Конструкция аккумулятора,Макс. время воспроизведения видео,Макс. время воспроизведения аудио,Комплект поставки,Чехол,Перо (стилус),Модель,Метки
0,Телефон Apple iPhone 16 Pro Max 256GB (природн...,2024 г.,✅ Дизайн и размер\niPhone 16 Pro Max оснащен у...,iOS,iOS 18,"6.9""",1320x2868,OLED (Super Retina XDR),120 Гц,8 ГБ,...,Li-ion,4 685 мА·ч,несъемный,33 ч,105 ч,"кабель USB-C - USB-C, скрепка, документация",No,No,Apple iPhone 16 Pro Max,"Onliner рекомендует, флагман, игровой, 256 ГБ,..."

In [93]:
characteristics_table = pd.DataFrame(columns=model_row.keys())
characteristics_table
characteristics_table = pd.concat([characteristics_table, pd.DataFrame(model_row)], axis=1)
characteristics_table

ValueError: If using all scalar values, you must pass an index